---
# tasks file for roles/elk
- name: Add Elasticsearch repository
  ansible.builtin.yum_repository:
    name: elasticsearch
    description: "Elasticsearch repository"
    baseurl: "https://artifacts.elastic.co/packages/8.x/yum"
    enabled: 1
    gpgcheck: 1
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    repo_gpgcheck: 1
    state: present

- name: Install Elasticsearch
  ansible.builtin.yum:
    name: elasticsearch
    state: present
  become: true

- name: Install Logstash
  ansible.builtin.yum:
    name: logstash
    state: present
  become: true

- name: Install Kibana
  ansible.builtin.yum:
    name: kibana
    state: present
  become: true

- name: Ensure Logstash configuration exists
  ansible.builtin.stat:
    path: /etc/logstash/conf.d/logstash.conf
  register: logstash_conf

- name: Create a default logstash.conf if it doesn't exist
  ansible.builtin.copy:
    dest: /etc/logstash/conf.d/logstash.conf
    content: |
      input {
        stdin { }
      }

      output {
        stdout {
          codec => rubydebug
        }
      }
  when: not logstash_conf.stat.exists
  notify:
    - Restart Logstash

- name: Start Elasticsearch service
  ansible.builtin.service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Start Logstash service
  ansible.builtin.service:
    name: logstash
    state: started
    enabled: yes

- name: Start Kibana service
  ansible.builtin.service:
    name: kibana
    state: started
    enabled: yes

