---
- name: Install EPEL release
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present
  notify:
    - Start nginx

- name: Ensure firewalld is started and enabled
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: Open required firewall ports
  ansible.builtin.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    zone: public
  loop:
    - 80/tcp
    - 443/tcp
  notify: Reload Firewalld

- name: Ensure nginx is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy Web Server
  ansible.builtin.copy:
    src: index.html
    dest: /usr/share/nginx/html
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart nginx